package com.jykito.industrialcore;

import com.jykito.industrialcore.item.ModItems;
import com.jykito.industrialcore.item.custom.ElectricDrillItem;
import com.jykito.industrialcore.item.custom.ElectricWrenchItem;
import com.jykito.industrialcore.item.custom.IndustrialDrillItem;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.material.Fluid;
import net.minecraft.world.level.material.Fluids;
import net.minecraftforge.common.capabilities.ForgeCapabilities;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.fluids.FluidUtil;
import net.minecraftforge.fluids.capability.IFluidHandlerItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public final class ModCreativeTab {

    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, IndustrialCore.MODID);

    public static final RegistryObject<CreativeModeTab> INDUSTRIAL_TAB =
            CREATIVE_MODE_TABS.register("industrial_tab", () -> CreativeModeTab.builder()
                    .withTabsBefore(CreativeModeTabs.SPAWN_EGGS)
                    .title(Component.translatable("creativetab.industrial_tab"))
                    .icon(() -> new ItemStack(ModItems.MACHINE_CASING_ITEM.get()))
                    .displayItems((parameters, output) -> {

                        output.accept(ModItems.MACHINE_CASING_ITEM.get());
                        output.accept(ModItems.COAL_GENERATOR_ITEM.get());
                        output.accept(ModItems.THERMOGENERATOR_ITEM.get());
                        output.accept(ModItems.MOD_BLAST_FURNACE_ITEM.get());
                        output.accept(ModItems.SOLAR_PANEL_T1_ITEM.get());
                        output.accept(ModItems.SOLAR_PANEL_T2_ITEM.get());
                        output.accept(ModItems.SOLAR_PANEL_T3_ITEM.get());
                        output.accept(ModItems.SOLAR_PANEL_T4_ITEM.get());
                        output.accept(ModItems.SOLAR_PANEL_T5_ITEM.get());
                        output.accept(ModItems.SOLAR_PANEL_T6_ITEM.get());
                        output.accept(ModItems.SOLAR_PANEL_T7_ITEM.get());
                        output.accept(ModItems.SOLAR_PANEL_T8_ITEM.get());
                        output.accept(ModItems.SOLAR_PANEL_T9_ITEM.get());
                        output.accept(ModItems.SOLAR_PANEL_T10_ITEM.get());
                        output.accept(ModItems.PANEL_COMBINER_ITEM.get());
                        output.accept(ModItems.CRUSHER_ITEM.get());
                        output.accept(ModItems.ELECTRIC_FURNACE_ITEM.get());
                        output.accept(ModItems.COMPRESSOR_ITEM.get());
                        output.accept(ModItems.METAL_FORMER_ITEM.get());
                        output.accept(ModItems.FlUID_ENRICHER.get());
                        output.accept(ModItems.LIQUEFIER_ITEM.get());
                        output.accept(ModItems.LAVA_GENERATOR_ITEM.get());
                        output.accept(ModItems.WATER_GENERATOR_ITEM.get());
                        output.accept(ModItems.STONE_GENERATOR_ITEM.get());
                        output.accept(ModItems.CAPSULE_FILLER_ITEM.get());
                        output.accept(ModItems.CULTIVATOR_ITEM.get());
                        output.accept(ModItems.ORE_WASHER_ITEM.get());
                        output.accept(ModItems.RECIPE_EXPORTER_ITEM.get());
                        output.accept(ModItems.ROD_FABRICATOR_ITEM.get());
                        output.accept(ModItems.EXTRACTOR_ITEM.get());
                        output.accept(ModItems.PHASE_SPLITTER_ITEM.get());
                        output.accept(ModItems.RESTRUCTOR_ITEM.get());
                        output.accept(ModItems.MATTER_FABRICATOR_ITEM.get());
                        output.accept(ModItems.BATTERY_CHARGER.get());
                        output.accept(ModItems.MINER_CASING_ITEM.get());
                        output.accept(ModItems.MINER_CORE_ITEM.get());
                        output.accept(ModItems.MINER_LENS_1.get());
                        output.accept(ModItems.MINER_LENS_2.get());
                        output.accept(ModItems.MINER_LENS_3.get());
                        output.accept(ModItems.MINER_LENS_4.get());
                        output.accept(ModItems.REACTOR_CHAMBER_ITEM.get());
                        output.accept(ModItems.NUCLEAR_REACTOR_ITEM.get());

                        output.accept(ModItems.TIN_ORE_ITEM.get());
                        output.accept(ModItems.DEEPSLATE_TIN_ORE_ITEM.get());
                        output.accept(ModItems.RAW_TIN.get());
                        output.accept(ModItems.RAW_TIN_BLOCK_ITEM.get());
                        output.accept(ModItems.LEAD_ORE_ITEM.get());
                        output.accept(ModItems.DEEPSLATE_LEAD_ORE_ITEM.get());
                        output.accept(ModItems.RAW_LEAD.get());
                        output.accept(ModItems.RAW_LEAD_BLOCK_ITEM.get());
                        output.accept(ModItems.BAUXITE_ORE_ITEM.get());
                        output.accept(ModItems.DEEPSLATE_BAUXITE_ORE_ITEM.get());
                        output.accept(ModItems.RAW_ALUMINUM.get());
                        output.accept(ModItems.URANIUM_ORE_ITEM.get());
                        output.accept(ModItems.DEEPSLATE_URANIUM_ORE_ITEM.get());
                        output.accept(ModItems.RAW_URANIUM.get());
                        output.accept(ModItems.RAW_URANIUM_BLOCK_ITEM.get());

                        output.accept(ModItems.TIN_INGOT.get());
                        output.accept(ModItems.LEAD_INGOT.get());
                        output.accept(ModItems.URANIUM_INGOT.get());
                        output.accept(ModItems.KRONIUM_ALLOY.get());
                        output.accept(ModItems.BRONZE_INGOT.get());
                        output.accept(ModItems.COMPOSITE_INGOT.get());
                        output.accept(ModItems.CRYSTAL_INGOT.get());
                        output.accept(ModItems.HARDENED_STEEL_INGOT.get());
                        output.accept(ModItems.KRONIT.get());
                        output.accept(ModItems.EXOTIC_MATTER.get());
                        output.accept(ModItems.IRON_DUST.get());
                        output.accept(ModItems.GOLD_DUST.get());
                        output.accept(ModItems.COPPER_DUST.get());
                        output.accept(ModItems.TIN_DUST.get());
                        output.accept(ModItems.LEAD_DUST.get());
                        output.accept(ModItems.BRONZE_DUST.get());
                        output.accept(ModItems.URANIUM_DUST.get());
                        output.accept(ModItems.DIAMOND_DUST.get());
                        output.accept(ModItems.EMERALD_DUST.get());
                        output.accept(ModItems.LAPIS_DUST.get());
                        output.accept(ModItems.COAL_DUST.get());
                        output.accept(ModItems.NETHERITE_DUST.get());
                        output.accept(ModItems.AMETHYST_DUST.get());
                        output.accept(ModItems.SILICON_DUST.get());
                        output.accept(ModItems.MINERAL_DUST.get());
                        output.accept(ModItems.SILICON.get());
                        output.accept(ModItems.ALUMINUM_DUST.get());
                        output.accept(ModItems.ALUMINUM_INGOT.get());
                        output.accept(ModItems.NICKEL_DUST.get());
                        output.accept(ModItems.NICKEL_INGOT.get());
                        output.accept(ModItems.SILVER_DUST.get());
                        output.accept(ModItems.SILVER_INGOT.get());
                        output.accept(ModItems.INVAR_INGOT.get());
                        output.accept(ModItems.ELECTRUM_INGOT.get());
                        output.accept(ModItems.NICKEL_BLOCK_ITEM.get());
                        output.accept(ModItems.SILVER_BLOCK_ITEM.get());
                        output.accept(ModItems.INVAR_BLOCK_ITEM.get());
                        output.accept(ModItems.ELECTRUM_BLOCK_ITEM.get());
                        output.accept(ModItems.LITHIUM_DUST.get());
                        output.accept(ModItems.LITHIUM.get());
                        output.accept(ModItems.PLUTONIUM.get());

                        output.accept(ModItems.IRON_PLATE.get());
                        output.accept(ModItems.COPPER_PLATE.get());
                        output.accept(ModItems.GOLD_PLATE.get());
                        output.accept(ModItems.TIN_PLATE.get());
                        output.accept(ModItems.LEAD_PLATE.get());
                        output.accept(ModItems.BRONZE_PLATE.get());
                        output.accept(ModItems.DIAMOND_PLATE.get());
                        output.accept(ModItems.EMERALD_PLATE.get());
                        output.accept(ModItems.LAPIS_PLATE.get());
                        output.accept(ModItems.NETHERITE_PLATE.get());
                        output.accept(ModItems.CRYSTAL_PLATE.get());
                        output.accept(ModItems.INVAR_PLATE.get());
                        output.accept(ModItems.ALUMINUM_PLATE.get());
                        output.accept(ModItems.ELECTRUM_PLATE.get());
                        output.accept(ModItems.COMPOSITE.get());
                        output.accept(ModItems.CARBON_FIBER.get());
                        output.accept(ModItems.CARBON_MESH.get());
                        output.accept(ModItems.CARBON_PLATE.get());
                        output.accept(ModItems.AMETHYST_CRYSTAL.get());
                        output.accept(ModItems.CRYSTAL_FIBER.get());
                        output.accept(ModItems.RUBBER.get());
                        output.accept(ModItems.TEXTOLITE_BOARD.get());
                        output.accept(ModItems.LOGIC_BOARD.get());
                        output.accept(ModItems.DATA_TRANSFER_MATRIX.get());
                        output.accept(ModItems.MICROCONTROLLER.get());
                        output.accept(ModItems.PHOTONIC_LENS.get());
                        output.accept(ModItems.SUPERCONDUCTOR_COIL.get());
                        output.accept(ModItems.QUANTUM_CAPACITOR.get());
                        output.accept(ModItems.SINGULARITY_CORE.get());
                        output.accept(ModItems.STELLAR_MATRIX.get());
                        output.accept(ModItems.ELECTRIC_MOTOR.get());
                        output.accept(ModItems.HEAT_CONDUCTOR.get());
                        output.accept(ModItems.ADVANCED_HEAT_EXCHANGER.get());

                        output.accept(ModItems.BARE_COPPER_WIRE.get());
                        output.accept(ModItems.BARE_FERRO_WIRE.get());
                        output.accept(ModItems.BARE_GOLD_WIRE.get());
                        output.accept(ModItems.BARE_CRYSTALLINE_WIRE.get());
                        output.accept(ModItems.BARE_EMERALD_WIRE.get());
                        output.accept(ModItems.BARE_HEAVY_WIRE.get());
                        output.accept(ModItems.BARE_NETHERITE_WIRE.get());
                        output.accept(ModItems.COPPER_CABLE_ITEM.get());
                        output.accept(ModItems.FERRO_CABLE_ITEM.get());
                        output.accept(ModItems.GOLD_CONDUCTOR_ITEM.get());
                        output.accept(ModItems.CRYSTALLINE_CHANNEL_ITEM.get());
                        output.accept(ModItems.EMERALD_FLUX_CABLE_ITEM.get());
                        output.accept(ModItems.HEAVY_MAGISTRAL_ITEM.get());
                        output.accept(ModItems.NETHERITE_FIBER_CABLE_ITEM.get());
                        output.accept(ModItems.ITEM_CONNECTOR_ITEM.get());
                        output.accept(ModItems.FLUID_CONNECTOR_ITEM.get());
                        output.accept(ModItems.LOGISTICS_NODE_ITEM.get());
                        output.accept(ModItems.LOGISTICS_LINKER.get());

                        output.accept(ModItems.CRATE_T1_ITEM.get());
                        output.accept(ModItems.CRATE_T2_ITEM.get());
                        output.accept(ModItems.CRATE_T3_ITEM.get());
                        output.accept(ModItems.BARREL_T1_ITEM.get());
                        output.accept(ModItems.BARREL_T2_ITEM.get());
                        output.accept(ModItems.BARREL_T3_ITEM.get());

                        output.accept(ModItems.RESIN_LOG_ITEM.get());
                        output.accept(ModItems.RESIN_LEAVES_ITEM.get());
                        output.accept(ModItems.RESIN_SAPLING_ITEM.get());
                        output.accept(ModItems.RESIN_COLLECTOR_ITEM.get());
                        output.accept(ModItems.TREE_RESIN.get());

                        output.accept(ModItems.TOOL_BASE.get());
                        output.accept(ModItems.IRON_DRILL_TIP.get());
                        output.accept(ModItems.NETHERITE_DRILL_TIP.get());
                        output.accept(ModItems.HAMMER.get());
                        output.accept(ModItems.CUTTERS.get());
                        output.accept(ModItems.ELECTRIC_WRENCH.get());
                        ItemStack fullWrench = new ItemStack(ModItems.ELECTRIC_WRENCH.get());
                        fullWrench.getOrCreateTag().putInt("energy", ElectricWrenchItem.CAPACITY);
                        output.accept(fullWrench);
                        output.accept(ModItems.ELECTRIC_DRILL.get());
                        ItemStack fullElectric = new ItemStack(ModItems.ELECTRIC_DRILL.get());
                        fullElectric.getOrCreateTag().putInt("energy", ElectricDrillItem.CAPACITY);
                        output.accept(fullElectric);
                        output.accept(ModItems.INDUSTRIAL_DRILL.get());
                        ItemStack fullIndustrial = new ItemStack(ModItems.INDUSTRIAL_DRILL.get());
                        fullIndustrial.getOrCreateTag().putInt("energy", IndustrialDrillItem.CAPACITY);
                        output.accept(fullIndustrial);

                        output.accept(ModItems.ITEM_PUSHER.get());
                        output.accept(ModItems.ITEM_PULLER.get());
                        output.accept(ModItems.FLUID_PUSHER.get());
                        output.accept(ModItems.FLUID_PULLER.get());
                        output.accept(ModItems.ACCELERATOR.get());
                        output.accept(ModItems.ACCELERATOR_MK1.get());
                        output.accept(ModItems.ACCELERATOR_MK2.get());
                        output.accept(ModItems.PARALLEL_MODULE.get());
                        output.accept(ModItems.ADVANCED_PARALLEL_MODULE.get());
                        output.accept(ModItems.QUANTUM_PARALLEL_MODULE.get());
                        output.accept(ModItems.BLAST_UPGRADE_FORCED_AIR.get());
                        output.accept(ModItems.BLAST_UPGRADE_OXYGEN_BOOST.get());
                        output.accept(ModItems.CULTIVATOR_BIOSTIMULATOR.get());
                        output.accept(ModItems.CULTIVATOR_RESONATOR.get());
                        output.accept(ModItems.CONNECTOR_UPGRADE_T1.get());
                        output.accept(ModItems.CONNECTOR_UPGRADE_T2.get());
                        output.accept(ModItems.CONNECTOR_UPGRADE_T3.get());
                        output.accept(ModItems.BASIC_CATALYST.get());
                        output.accept(ModItems.ACTIVATED_CATALYST.get());
                        output.accept(ModItems.RESONANT_CATALYST.get());
                        output.accept(ModItems.UNIVERSAL_CATALYST.get());

                        output.accept(ModItems.BATTERY.get());
                        ItemStack fullBattery = new ItemStack(ModItems.BATTERY.get());
                        fullBattery.getOrCreateTag().putInt("energy", 10000);
                        output.accept(fullBattery);
                        output.accept(ModItems.LITHIUM_BATTERY.get());
                        ItemStack fullLithium = new ItemStack(ModItems.LITHIUM_BATTERY.get());
                        fullLithium.getOrCreateTag().putInt("energy", 50000);
                        output.accept(fullLithium);
                        output.accept(ModItems.ENERGY_CRYSTAL.get());
                        ItemStack fullCrystal = new ItemStack(ModItems.ENERGY_CRYSTAL.get());
                        fullCrystal.getOrCreateTag().putInt("energy", 100000);
                        output.accept(fullCrystal);
                        output.accept(ModItems.LAPOTRON_CRYSTAL.get());
                        ItemStack fullLapotron = new ItemStack(ModItems.LAPOTRON_CRYSTAL.get());
                        fullLapotron.getOrCreateTag().putInt("energy", 500000);
                        output.accept(fullLapotron);
                        output.accept(ModItems.ENERGY_BACKPACK_T1.get());
                        output.accept(ModItems.ENERGY_BACKPACK_T2.get());
                        output.accept(ModItems.ENERGY_BACKPACK_T3.get());

                        output.accept(ModItems.EMPTY_FUEL_ROD.get());
                        output.accept(ModItems.EMPTY_REINFORCED_FUEL_ROD.get());
                        output.accept(ModItems.URANIUM_FUEL_ROD.get());
                        output.accept(ModItems.DEPLETED_URANIUM_FUEL_ROD.get());
                        output.accept(ModItems.PLUTONIUM_FUEL_ROD.get());
                        output.accept(ModItems.DEPLETED_PLUTONIUM_FUEL_ROD.get());
                        output.accept(ModItems.MOX_FUEL.get());
                        output.accept(ModItems.MOX_FUEL_ROD.get());
                        output.accept(ModItems.DEPLETED_MOX_FUEL_ROD.get());
                        output.accept(ModItems.GRAPHITE_ROD.get());
                        output.accept(ModItems.HEAT_VENT.get());
                        output.accept(ModItems.INTEGRAL_HEAT_VENT.get());
                        output.accept(ModItems.HEAT_EXCHANGER.get());
                        output.accept(ModItems.COMPONENT_HEAT_VENT.get());
                        output.accept(ModItems.ADVANCED_HEAT_VENT.get());
                        output.accept(ModItems.CONDENSATOR.get());
                        output.accept(ModItems.REACTOR_BLUEPRINT.get());
                        output.accept(ModItems.REACTOR_SCHEME_U1.get());
                        output.accept(ModItems.REACTOR_SCHEME_U2.get());
                        output.accept(ModItems.REACTOR_SCHEME_U3.get());
                        output.accept(ModItems.REACTOR_SCHEME_P1.get());
                        output.accept(ModItems.REACTOR_SCHEME_P2.get());
                        output.accept(ModItems.REACTOR_SCHEME_P3.get());
                        output.accept(ModItems.REACTOR_SCHEME_P4.get());
                        output.accept(ModItems.REACTOR_SCHEME_M1.get());
                        output.accept(ModItems.REACTOR_SCHEME_M2.get());
                        output.accept(ModItems.REACTOR_SCHEME_M3.get());
                        output.accept(ModItems.REACTOR_SCHEME_M4.get());

                        output.accept(ModItems.PLASMA_HELMET.get());
                        ItemStack fullPlasmaHelmet = new ItemStack(ModItems.PLASMA_HELMET.get());
                        fullPlasmaHelmet.getOrCreateTag().putInt("Energy", com.jykito.industrialcore.item.custom.PlasmaArmorItem.CAPACITY);
                        output.accept(fullPlasmaHelmet);
                        output.accept(ModItems.PLASMA_CHESTPLATE.get());
                        ItemStack fullPlasmaChest = new ItemStack(ModItems.PLASMA_CHESTPLATE.get());
                        fullPlasmaChest.getOrCreateTag().putInt("Energy", com.jykito.industrialcore.item.custom.PlasmaArmorItem.CAPACITY);
                        output.accept(fullPlasmaChest);
                        output.accept(ModItems.PLASMA_LEGGINGS.get());
                        ItemStack fullPlasmaLegs = new ItemStack(ModItems.PLASMA_LEGGINGS.get());
                        fullPlasmaLegs.getOrCreateTag().putInt("Energy", com.jykito.industrialcore.item.custom.PlasmaArmorItem.CAPACITY);
                        output.accept(fullPlasmaLegs);
                        output.accept(ModItems.PLASMA_BOOTS.get());
                        ItemStack fullPlasmaBoots = new ItemStack(ModItems.PLASMA_BOOTS.get());
                        fullPlasmaBoots.getOrCreateTag().putInt("Energy", com.jykito.industrialcore.item.custom.PlasmaArmorItem.CAPACITY);
                        output.accept(fullPlasmaBoots);
                        output.accept(ModItems.NEXITE_HELMET.get());
                        ItemStack fullNexHelmet = new ItemStack(ModItems.NEXITE_HELMET.get());
                        fullNexHelmet.getOrCreateTag().putInt("Energy", com.jykito.industrialcore.item.custom.NexiteArmorItem.CAPACITY);
                        output.accept(fullNexHelmet);
                        output.accept(ModItems.NEXITE_CHESTPLATE.get());
                        ItemStack fullNexChest = new ItemStack(ModItems.NEXITE_CHESTPLATE.get());
                        fullNexChest.getOrCreateTag().putInt("Energy", com.jykito.industrialcore.item.custom.NexiteArmorItem.CAPACITY);
                        output.accept(fullNexChest);
                        output.accept(ModItems.NEXITE_LEGGINGS.get());
                        ItemStack fullNexLegs = new ItemStack(ModItems.NEXITE_LEGGINGS.get());
                        fullNexLegs.getOrCreateTag().putInt("Energy", com.jykito.industrialcore.item.custom.NexiteArmorItem.CAPACITY);
                        output.accept(fullNexLegs);
                        output.accept(ModItems.NEXITE_BOOTS.get());
                        ItemStack fullNexBoots = new ItemStack(ModItems.NEXITE_BOOTS.get());
                        fullNexBoots.getOrCreateTag().putInt("Energy", com.jykito.industrialcore.item.custom.NexiteArmorItem.CAPACITY);
                        output.accept(fullNexBoots);

                        output.accept(ModItems.UNIVERSAL_CAPSULE.get());
                        for (Fluid fluid : ForgeRegistries.FLUIDS.getValues()) {
                            if (fluid == Fluids.EMPTY || !fluid.isSource(fluid.defaultFluidState())) continue;
                            ItemStack fullCapsule = new ItemStack(ModItems.UNIVERSAL_CAPSULE.get());
                            fullCapsule.getCapability(ForgeCapabilities.FLUID_HANDLER_ITEM).ifPresent(handler ->
                                    handler.fill(new FluidStack(fluid, 1000), IFluidHandlerItem.FluidAction.EXECUTE));
                            output.accept(fullCapsule);
                        }
                    }).build());

    private ModCreativeTab() {}
}
